extends: free_sphere_r125_2b_a0_coverage_no23.yaml
run_name: corrected_package_a_r125_2b_Apos_no_position
model_config: ../model/brian_r125_sphere16_no_position.yaml
loss_weights:
  location: 0.0
wandb:
  group: corrected_package_a_r125_2b
  tags: [corrected_package_a, r125, 2b, Apos, coverage_warmup, no_position]
