extends: ablation_a7_no_location_loss.yaml
run_name: package_a_r125_2b_A7_no_location_loss
data_config: ../data/r125_main_2b.yaml
max_steps: 244141
eval_interval: 10000
save_interval: 10000
save_best_checkpoint: false
wandb:
  group: package_a_r125_2b
  tags: [package_a, r125, 2b, A7, no_location_loss]
