extends: stage3_scheduled_free_routing.yaml
run_name: package_a_r125_2b_A4_free_router_block_position
data_config: ../data/r125_main_2b.yaml
batch_size: 32
max_steps: 30518
eval_interval: 2500
save_interval: 2500
save_best_checkpoint: false
wandb:
  group: package_a_r125_2b_bs32
  tags: [package_a, r125, 2b, bs32, A4, free_router_block_position]
