extends: smoke_q8_cpbc_r125_250m_dp_u1_c2048_per_head_d32_ddp2.yaml
run_name: smoke_q10_cpbc_r125_5b_dp_u1_c2048_per_head_d64_ddp2
output_root: tmp/runs_q10_cpbc_per_head_dp_c2048_d64_smoke
model_config: ../model/brian_r125_bdre_cpbc_dp_c2048_per_head_triton_recompute_d64.yaml
