extends: smoke_grouped_dense_fastlog_nounused_weightcache_gather_tf32_router1_routedcompile_r125_5b_ddp2_legacyval.yaml
run_name: smoke_grouped_dense_fastlog_nounused_weightcache_gather_tf32_router1_routedcompile_b8acc1_r125_5b_ddp4_legacyval
batch_size: 8
gradient_accumulation_steps: 1
