extends: smoke_cpbc_r125_5b_dp_u1_c2048_grouped_mm_gpu_static_blockmask_incremental_ddp2_legacyval.yaml
run_name: smoke_cpbc_r125_5b_dp_u1_c2048_triton_fused_reader_incremental_ddp2_legacyval
model_config: ../model/brian_r125_bdre_cpbc_dp_c2048_triton_fused_reader_incremental.yaml
output_root: tmp/runs_cpbc_dp_triton_fused_reader_c2048_ddp2_smoke
