extends: stage5_bdre_tiny_synchronous_prefix_ddp2_debug.yaml
run_name: stage5_bdre_tiny_cpbc_fb_u2_ddp2_debug
model_config: ../model/brian_tiny_bdre_cpbc_fb.yaml

stateful_tbptt:
  detach_interval_chunks: 2
